
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_Strong_Password_123
    ports:
      - "1433:1433"

  foreignexchange:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: foreignexchange
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ForeignExchange;User=sa;Password=Your_Strong_Password_123;TrustServerCertificate=True
      - JwtSettings__SecretKey=pM6+Nw8zFfV1J3hYBvLq9E5X4a7UoCmK4sG2RkTzPdQ=
      - JwtSettings__Issuer=swagger-test
      - JwtSettings__Audience=swagger-users
      - JwtSettings__ExpirationTime=3600
      - AlphaVantage__ApiKey=KEY
      - AlphaVantage__BaseUrl=https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency={0}&to_currency={1}&apikey={2}  
      - AzureServiceBus__ConnectionString=Endpoint=sb://your-servicebus-name.servicebus.windows.net/;SharedAccessKeyName=your-key-name;SharedAccessKey=your-key
      - AzureServiceBus__QueueName=exchange-rates-queue
      - EncryptHashing__SaltSize=16
      - EncryptHashing__IterationCount=10000
      - EncryptHashing__KeySize=32
      - EncryptHashing__Pepper=YourSuperSecureSecretKey
    command: >
      sh -c "dotnet ef database update --project ForeignExchange.Infrastructure/ForeignExchange.Infrastructure.csproj --startup-project ForeignExchange/ForeignExchange.csproj &&
      dotnet /app/publish/ForeignExchange.dll"
