
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_Strong_Password_123
    ports:
      - "1433:1433"

  foreignexchange:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: foreignexchange
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    command: >
      sh -c "dotnet ef database update --project ForeignExchange.Infrastructure/ForeignExchange.Infrastructure.csproj --startup-project ForeignExchange/ForeignExchange.csproj &&
      dotnet /app/publish/ForeignExchange.dll"
